### ISSUE TITLE
[aide] Comment utiliser PicoFarad pour REST API

### ISSUE THREAD

**Issue by meradoou** [fguillot/picoFarad#2]
Bonjour,
J'ai essayé de faire comme sur la documentation mais pas de resultat. J'ai été obligé de faire comme ceci et sans url_rewrite pour avoir un peu de resultat

```
Router\put('index.php/foo/:id', function($id) {
// data
});
```
Merci

**Comment by fguillot** [comment]
Si tu utilises Apache il faut activer le mod_rewrite pour avoir des urls sans le index.php

Tu as des exemples de config ici: http://silex.sensiolabs.org/doc/web_servers.html

**Comment by meradoou** [comment]
Effectivement, j'ai oublié d'activer le mod_rewrite d'apache et aussi que ceci était encore ouvert.
